### ISSUE TITLE
Please remove bold claim "on par with Aba-pro"

### ISSUE THREAD

**Issue by peso** [Cotix/Abalone#3]
In the readme it says "performance is already up to par, or better then ABA-PRO".

Well, performance, what is that? To most people, better performance means stronger play (wins most of the time). I'm pretty sure this is not yet the case.

Performance and search depth are only related, if you don't loose quality of moves. Often it is a trade-off.

I suggest you remove that sentence.

For information, Aba-Pro is probably the second strongest Abalone program in the world. David Malek reported that his program, My Lovely Abalone (MLA) has beaten Aba-Pro in a tournament game (2007). I'm not aware of any official challenge, though.

MLA uses MTD(f) search, as far as I know.

**Comment by Cotix** [comment]
I think your point is correct, and I just removed the claim. What I meant by performance was more related to board/s evaluated.
